name: Banking CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake lcov
        
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake -DBUILD_TESTING=ON ..
        
    - name: Build
      run: |
        cd build
        cmake --build . --target banking_tests
        
    - name: List tests (debug)
      run: |
        cd build
        ctest -N
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure -V
        
    - name: Generate coverage
      run: |
        cd build
        lcov --capture --directory banking/CMakeFiles/banking.dir/src --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
        genhtml coverage.info --output-directory coverage_report
        
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage_report
