name: Banking CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake lcov
        
    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON ..
        cmake --build . --target banking_tests
        
    - name: List registered tests
      run: |
        cd build
        ctest -N
        
    - name: Run tests with verbose output
      run: |
        cd build
        ./banking/tests/banking_tests --gtest_output=xml:test_results.xml
        ctest --output-on-failure -V
        
    - name: Generate coverage report
      run: |
        cd build
        #  Создаем директорию для coverage данных
        mkdir -p coverage_data
    
        # Копируем .gcda и .gcno файлы в одну директорию
        find . -name "*.gcda" -exec cp --parents {} coverage_data \;
        find . -name "*.gcno" -exec cp --parents {} coverage_data \;
    
        # Генерируем отчет из собранных файлов
        lcov --capture \
           --directory coverage_data \
           --output-file coverage.info \
           --rc branch_coverage=1
    
        # Фильтруем результаты
        lcov --remove coverage.info \
           '/usr/*' \
           '*/tests/*' \
           --output-file coverage.info \
           --rc branch_coverage=1
    
        # Генерируем HTML отчет
        genhtml coverage.info \
            --output-directory coverage_report \
            --branch-coverage \
            --legend
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage_report
